person_identifier: "person"
threshold: 0.5
possible_classes:
  - 
    simple1: [person, bicycle, bench, backpack, umbrella, handbag, suitcase, sports ball, tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple, sandwich, orange]
  - 
    simple2: [broccoli, carrot, hot dog, pizza, donut, cake, chair, sofa, pottedplant, bed, diningtable, toilet, tvmonitor, laptop, mouse, remote, keyboard, cell phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear, hair drier, toothbrush]
