subscribers:

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1

publishers:

  object_recognition:
    topic: /vision_system/or/object_recognition
    queue_size: 1

  object_recognition3d:
    topic: /vision_system/or/object_recognition3d
    queue_size: 1

  people_detection:
    topic: /vision_system/or/people_detection
    queue_size: 1

  object_list_updated:
    topic: /vision_system/fr/object_list_updated
    queue_size: 1

servers:

  list_objects:
    service: /vision_system/fr/list_objects