people_tracking:
  thresholds:
    bounding_box_size: 0.1
    probability: 0.7
  match:
    minimal_hessian: 400
    minimal_minimal_distance: 0.2
    check_factor: 0.7
    k: 8
  detector:
    type: "sift"