subscribers:

  camera_reading:
    topic: /vision_system/vsb/image_rgb_raw
    queue_size: 1
  
  classifier_reload:
    topic: /vision_system/fr/classifier_reload
    queue_size: 1

publishers:

  face_recognition:
    topic: /vision_system/fr/face_recognition
    queue_size: 1

  face_recognition_view:
    topic: /vision_system/fr/face_recognition_view
    queue_size: 1

  classifier_reload:
    topic: /vision_system/fr/classifier_reload
    queue_size: 1

services:

  classifier_training:
    service: /vision_system/fr/classifier_training